fname='TestPlan'

TestPlan.pdf:
	pdflatex $(fname).tex

clean:
	rm -f $(fname).log
	rm -f $(fname).lot
	rm -f $(fname).out
	rm -f $(fname).toc
	rm -f $(fname).bbl
	rm -f $(fname).aux
	rm -f $(fname).lof
	rm -f $(fname).pdf
